export default [
  {
    id: 1,
    name: "1101",
    description: "Leitura dificultada por caes/animais",
    reading: true,
  },
  {
    id: 2,
    name: "1102",
    description: "Medidor obstruído com possibilidade de leitura",
    reading: true,
  },
  {
    id: 3,
    name: "1103",
    description: "Falta placa/identif. medidor/quadro/apto./prédio",
    reading: true,
  },
  {
    id: 4,
    name: "1104",
    description: "Medição/Quadro em mau estado",
    reading: true,
  },
  {
    id: 5,
    name: "1105",
    description: "Falta iluminação/limpeza",
    reading: true,
  },
  {
    id: 6,
    name: "1107",
    description: "Med local impróprio perigoso/Cx med altura anormal",
    reading: true,
  },
  {
    id: 7,
    name: "1120",
    description: "Suspeita de criadouro da DENGUE",
    reading: true,
  },
  {
    id: 8,
    name: "1201",
    description: "Mudança nome logradouro",
    reading: true,
  },
  {
    id: 9,
    name: "1202",
    description: "Mudança numeração interna, apto ou vila de casas",
    reading: true,
  },
  {
    id: 10,
    name: "1203",
    description: "Instalação fora de sequencia",
    reading: true,
  },
  {
    id: 11,
    name: "1204",
    description: "Num. medidor/constante diferente sem substituição",
    reading: true,
  },
  {
    id: 99,
    name: "1205",
    description: "Medidor substituido",
    reading: true,
  },
  {
    id: 12,
    name: "1206",
    description: "Codigo de classe/ramo de negocio inadequado",
    reading: true,
  },
  {
    id: 13,
    name: "1207",
    description: "Cliente não cadastrado/Nova ligação",
    reading: true,
  },
  {
    id: 14,
    name: "1208",
    description: "Sequenciamento de Rota",
    reading: true,
  },
  {
    id: 15,
    name: "1231",
    description: "Inversão de medidores entre instalações",
    reading: true,
  },
  {
    id: 16,
    name: "1234",
    description: "Endereço urbano para entrega de fatura rural",
    reading: true,
  },
  {
    id: 17,
    name: "1250",
    description: "Inclusão/alterações local instalações do equipamento",
    reading: true,
  },
  {
    id: 18,
    name: "1302",
    description: "Ramal aereo com obstaculos",
    reading: true,
  },
  {
    id: 19,
    name: "1303",
    description: "Fornecimento a terceiros/interligação",
    reading: true,
  },
  {
    id: 20,
    name: "1304",
    description: "Consumo em instalação desligada",
    reading: true,
  },
  {
    id: 21,
    name: "1305",
    description: "Auto relig. s/contrato ligado sistema",
    reading: true,
  },
  {
    id: 22,
    name: "1320",
    description: "Situação de risco para terceiros na rede",
    reading: true,
  },
  {
    id: 23,
    name: "1326",
    description: "Vespeiro na medição",
    reading: true,
  },
  {
    id: 24,
    name: "1327",
    description: "Vidro visor quebrado",
    reading: true,
  },
  {
    id: 25,
    name: "1329",
    description: "Medidor embaçado",
    reading: true,
  },
  {
    id: 26,
    name: "1343",
    description: "Iluminação publica acesa durante o dia",
    reading: true,
  },
  {
    id: 27,
    name: "1349",
    description: "Instalação com ligação provisoria",
    reading: true,
  },
  {
    id: 28,
    name: "1351",
    description: "Suspeita de medidor com ponteiros desregulados",
    reading: true,
  },
  {
    id: 29,
    name: "1364",
    description: "Vidro visor da caixa embaçado",
    reading: true,
  },
  {
    id: 30,
    name: "1373",
    description: "Instalação incendiada/demolidas",
    reading: true,
  },
  {
    id: 31,
    name: "1390",
    description: "Med posicionado inadequadamente na caixa",
    reading: true,
  },
  {
    id: 32,
    name: "1501",
    description: "Medidor sem caixa/tampa",
    reading: true,
  },
  {
    id: 33,
    name: "1502",
    description: "Caixa de mediçao sem selo",
    reading: true,
  },
  {
    id: 34,
    name: "1503",
    description: "Suspeita de irregularidade",
    reading: true,
  },
  {
    id: 35,
    name: "1504",
    description: "Instalação ligada direta",
    reading: true,
  },
  {
    id: 36,
    name: "1505",
    description: "Suspeita med defeituoso/avariado/manipulado/parado",
    reading: true,
  },
  {
    id: 37,
    name: "1506",
    description: "Medidor com disco girando ao contrario/desmarcando",
    reading: true,
  },
  {
    id: 38,
    name: "1544",
    description: "Nao identificado motivo do consumo zero",
    reading: true,
  },
  {
    id: 39,
    name: "1546",
    description: "Consumo incompativel com o imovel",
    reading: true,
  },
  {
    id: 40,
    name: "1560",
    description: "Denuncia de uma ligação clandestina",
    reading: true,
  },
  {
    id: 41,
    name: "1562",
    description: "Instalação desligada sem consumo",
    reading: true,
  },
  {
    id: 42,
    name: "1570",
    description: "Denuncia de varias ligações clandestinas",
    reading: true,
  },
  {
    id: 43,
    name: "3201",
    description: "Medidor retirado",
    reading: false,
  },
  {
    id: 44,
    name: "3205",
    description: "End. instalação n/localizado/Instal alocada errada",
    reading: false,
  },
  {
    id: 45,
    name: "3245",
    description: "Instalação inexistente sem ramal e sem medição",
    reading: false,
  },
  {
    id: 46,
    name: "3301",
    description: "Medidor eletronico sem funcao auxilar",
    reading: false,
  },
  {
    id: 47,
    name: "3311",
    description: "Medidor eletronico apagado/chave desligada",
    reading: false,
  },
  {
    id: 48,
    name: "3312",
    description: "Medidor com disco girando ao contrario/desmarcando",
    reading: false,
  },
  {
    id: 49,
    name: "3313",
    description: "Insetos dentro da caixa ou envolvendo o medidor",
    reading: false,
  },
  {
    id: 50,
    name: "3369",
    description: "Medidor embaçado ",
    reading: false,
  },
  {
    id: 51,
    name: "3374",
    description: "Vidro visor da caixa embaçado",
    reading: false,
  },
  {
    id: 52,
    name: "3376",
    description: "Medidor eletronico desprogramado",
    reading: false,
  },
  {
    id: 53,
    name: "3379",
    description: "Med posicionado inadequadamente na caixa",
    reading: false,
  },
];
